name: second

services:
    db:
        image: mysql:8.3.0
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpressdb
            MYSQL_USER: exempleuser
            MYSQL_PASSWORD: exemplepass
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "9000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: exempleuser
            WORDPRESS_DB_PASSWORD: exemplepass
            WORDPRESS_DB_NAME: wordpressdb
        working_dir: /var/www/html
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        ports: 
            - "9080:80"
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: wordpress

volumes: 
    db_data:
