name: second

services:
    
    db:
        image: mysql:latest
        container_name: mysql_server
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports: 
            - "3396:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=springboot
        networks:
            - backend
            
    apiprojet:
        image: esalcue/api:latest
        container_name: apiprojet
        restart: on-failure
        ports:
            - "9010:9000"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springboot
            
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
            - SPRING_JPA_SHOW_SQL=true
            - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
        
        depends_on:
            - db
        networks:
            - backend
            
    webprojet:
        image: esalcue/webspringboot2025:latest
        container_name: webprojet
        ports:
            - "9090:9090"
        depends_on:
            - apiprojet
        environment:
            - FR.AFPA.POMPEY.CDA.APPWEB.URLAPI= http://apiprojet:9000
        healthcheck:
            test: curl -f http://apiproject:9000/persons || exit 1
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 10s
        networks:
            - backend

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        ports: 
            - "9080:80"
        restart: always
        environment:
            PMA_HOST: "db"
            MYSQL_ROOT_PASSWORD: "root"
        networks:
            - backend

volumes: 
    db_data:

networks:
    backend:
        driver: bridge
